### PR TITLE
Failure to compile firmware "NE" back on "NO"

### PR DESCRIPTION
**Pull request by stanekTM**
The "NE" translation "CZ" menu for "Mode" and "X-Any" causes an error

### CODE REVIEW

**Comment by Ingwie** [comment]
Hi George,
This pull request delete ALL the files of OpenAVRc project :scream: .
All your modifications are recorded with Github ...
Closed.

**Comment by stanekTM** [comment]
Hi,
Sorry, I just wanted to press two files, and it doesn't work.
Well, I will not push here anymore and I'd rather send it to a forum or elsewhere.
George :(

**Comment by Ingwie** [comment]
Yes, i have understood what you wanted to do.

To add a file by pull request : Add the file to a complete fork (do not delete anythink).

Of course you can send me the file by MP.

Thank you George ;-) 

P.S : I have changed "CompilOmatic" code : All needed compilations parameter are "protected" -> No possible translation now. Thanks again for that.

**Comment by stanekTM** [comment]
Well, thanks for your patience :+1:

**Pull request closed without merging**
