### PR TITLE
added bayang support with telemetry

### PR DESCRIPTION
**Pull request by payalneg**
Added support for Bayang protocol on spi module NRF24L01

### CODE REVIEW

**Comment by Ingwie** [comment]
All is working ?
I can't test it ...

**Comment by payalneg** [comment]
Yeap, tested on NFE silverware and PC simulator. Photo of telemetry:
image

**Comment by Ingwie** [comment]
Perfect !
Thanks for all OpenAVRc users ;-)

**Comment by pierrotm777** [comment]
Hello payalneg,

Thanks for this wonderful add. How do you configure the CE pin ? Just with a pull up i suppose ?

**Comment by payalneg** [comment]
> Hello payalneg,
> 
> Thanks for this wonderful add. How do you configure the CE pin ? Just with a pull up i suppose ?

yes, just pull up to VCC

**Comment by pierrotm777** [comment]
OK, Thanks

**Comment by stanekTM** [comment]
Thank you for SPI nRF24L01

**Pull request merged**
