### PR TITLE
Added links to translations and update translations "CZ"

### PR DESCRIPTION
**Pull request by stanekTM**

### CODE REVIEW

**Comment by Ingwie** [comment]
Why are they conflicts ? Do you used the last files ?
If take time to resolve it ...
Your mods in OpenAVRc_DesktopMain.cpp are perfect,

**Comment by stanekTM** [comment]
I have no idea they are ok :(

**Comment by Ingwie** [comment]
Ok, i will resolve them after lunch ;-)

**Comment by Ingwie** [comment]
You must not delete a file -> This file history is lost.
We use Github to store all the history : This help us to find when a bug arrive.
I close this pr, sorry George.

**Pull request closed without merging**
