### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by juanitobananas**
@Ingwie, I believe jmentero has told you who I am ;)

I think it is a nice thing to have a LICENSE (or COPYING) file in the root directory so that everybody can find it quickly, although you already mention that it is GPL-licensed, so that should've been enough.

Of course, feel free to ignore this PR or change it in any manner. I can also add/remove something if you don't like it.

Cheers

### CODE REVIEW

**Comment by Ingwie** [comment]
Hello and welcome Juan, i'm whith my familly and give a look later. Many thanks !

Le 27 décembre 2016 11:12:44 CET, juanitobananas <notifications@github.com> a écrit :
>@Ingwie, I believe jmentero has told you who I am ;)
>
>I think it is a nice thing to have a LICENSE (or COPYING) file in the
>root directory so that everybody can find it quickly, although you
>already mention that it is GPL-licensed, so that should've been enough.
>
>Of course, feel free to ignore this PR or change it in any manner. I
>can also add/remove something if you don't like it.
>
>Cheers
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/Ingwie/OpenAVRc_Dev/pull/4
>
>-- Commit Summary --
>
>  * Add GPLv2 LICENSE file in the root directory of git project.
>
>-- File Changes --
>
>    A LICENSE (344)
>
>-- Patch Links --
>
>https://github.com/Ingwie/OpenAVRc_Dev/pull/4.patch
>https://github.com/Ingwie/OpenAVRc_Dev/pull/4.diff
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Ingwie/OpenAVRc_Dev/pull/4

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by juanitobananas** [comment]
No problem!! :smile:

**Comment by Ingwie** [comment]
Thank you juanitobananas 👍 but, do you think "Gnomovision version 69" is useful ?  ;-)
Will modify tomorrow ....

**Comment by Ingwie** [comment]
Merged with little changes. Thank you Juan 👍

**Comment by juanitobananas** [comment]
> do you think "Gnomovision version 69" is useful ? ;-)

It does sound kinda cool, but it probably isn't useful :smile: 
That slipped. Sorry! :blush:

>Merged with little changes. Thank you Juan :+1:

You're welcome!

**Pull request merged**
