### PR TITLE
Added voice files "CZ"

### PR DESCRIPTION
**Pull request by stanekTM**
Thank you :+1:

### CODE REVIEW

**Comment by Ingwie** [comment]
Perfect, did you try?

**Comment by Ingwie** [comment]
Ho !! There are missing translations !!

eg : Pilotujete jako bůh !!

**Comment by stanekTM** [comment]
He tried only at the PC level.
I have not assembled the necessary hardware.
It's a copy of "EN".
Still compare with "FR" and add.
"tu voles comme un dieu" :+1: 
"L'air est notre mer"
George :+1:

**Comment by Ingwie** [comment]
:+1: 
If Simu play the file, it will work on the transmmiter ;-)
Christophe

**Pull request merged**
