### PR TITLE
Incorrect define name for power in nrf24l01 module

### PR DESCRIPTION
**Pull request by payalneg**

### CODE REVIEW

**Comment by Ingwie** [comment]
Hi,
Please update your fork before sending a pull request.

Here, you change just one line -> 5 files changed :question:

**Comment by Ingwie** [comment]
I do the change, thanks

**Comment by payalneg** [comment]
Sorry, it's my second pull request in my life. It will be great if you fix define name from NRF24L01_GAIN to NRF24L01PA_GAIN. Thnx.

**Comment by Ingwie** [comment]
Yes, don't worry.
I just want to keep a clear (as possible) code history

**Pull request closed without merging**
